# Generated by Django 5.2.17 on 2026-09-29 20:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=16, verbose_name="Номер корпуса"),
                ),
                ("floors", models.PositiveSmallIntegerField(verbose_name="Этажность")),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("project", "Проект"),
                            ("construction", "Строится"),
                            ("done", "Сдан"),
                        ],
                        default="construction",
                        max_length=16,
                        verbose_name="Стадия",
                    ),
                ),
                (
                    "completion_quarter",
                    models.CharField(
                        blank=True,
                        help_text="Например: IV кв. 2027",
                        max_length=16,
                        verbose_name="Срок сдачи",
                    ),
                ),
                (
                    "construction_progress",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Готовность, %"
                    ),
                ),
            ],
            options={
                "verbose_name": "Корпус",
                "verbose_name_plural": "Корпуса",
                "ordering": ("complex", "number"),
            },
        ),
        migrations.CreateModel(
            name="ResidentialComplex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Название")),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                (
                    "tagline",
                    models.CharField(blank=True, max_length=200, verbose_name="Слоган"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("address", models.CharField(max_length=255, verbose_name="Адрес")),
                (
                    "district",
                    models.CharField(blank=True, max_length=128, verbose_name="Район"),
                ),
                (
                    "metro",
                    models.CharField(blank=True, max_length=128, verbose_name="Метро"),
                ),
                (
                    "metro_minutes",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Минут до метро пешком"
                    ),
                ),
                (
                    "housing_class",
                    models.CharField(
                        choices=[
                            ("comfort", "Комфорт"),
                            ("business", "Бизнес"),
                            ("premium", "Премиум"),
                        ],
                        default="comfort",
                        max_length=16,
                        verbose_name="Класс жилья",
                    ),
                ),
                (
                    "completion_year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Год сдачи"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "features",
                    models.TextField(
                        blank=True, verbose_name="Особенности (по одной на строку)"
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#1f6feb", max_length=16, verbose_name="Акцентный цвет"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="complexes/", verbose_name="Обложка"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликован"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Жилой комплекс",
                "verbose_name_plural": "Жилые комплексы",
                "ordering": ("completion_year", "name"),
            },
        ),
        migrations.CreateModel(
            name="Apartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=16, verbose_name="Номер квартиры"),
                ),
                ("floor", models.PositiveSmallIntegerField(verbose_name="Этаж")),
                (
                    "rooms",
                    models.PositiveSmallIntegerField(
                        help_text="0 — студия", verbose_name="Комнат"
                    ),
                ),
                (
                    "area",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="Общая площадь, м²"
                    ),
                ),
                (
                    "living_area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="Жилая площадь, м²",
                    ),
                ),
                (
                    "kitchen_area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Площадь кухни, м²",
                    ),
                ),
                (
                    "ceiling_height",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2.8"),
                        max_digits=4,
                        verbose_name="Высота потолков, м",
                    ),
                ),
                (
                    "bathrooms",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Санузлов"
                    ),
                ),
                (
                    "balcony",
                    models.BooleanField(default=False, verbose_name="Балкон/лоджия"),
                ),
                (
                    "window_view",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Вид из окон"
                    ),
                ),
                (
                    "finishing",
                    models.CharField(
                        choices=[
                            ("none", "Без отделки"),
                            ("whitebox", "White box"),
                            ("fine", "Чистовая"),
                            ("furnished", "С мебелью"),
                        ],
                        default="none",
                        max_length=16,
                        verbose_name="Отделка",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Цена, ₽"
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Старая цена, ₽",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "В продаже"),
                            ("reserved", "Забронирована"),
                            ("sold", "Продана"),
                        ],
                        db_index=True,
                        default="available",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "plan_image",
                    models.ImageField(
                        blank=True, upload_to="plans/", verbose_name="Планировка"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apartments",
                        to="catalog.building",
                        verbose_name="Корпус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Квартира",
                "verbose_name_plural": "Квартиры",
                "ordering": ("price",),
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="catalog.apartment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Избранное",
                "verbose_name_plural": "Избранное",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="building",
            name="complex",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buildings",
                to="catalog.residentialcomplex",
                verbose_name="ЖК",
            ),
        ),
        migrations.AddIndex(
            model_name="apartment",
            index=models.Index(
                fields=["rooms", "price"], name="catalog_apa_rooms_688f9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apartment",
            index=models.Index(fields=["area"], name="catalog_apa_area_57b5d7_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="apartment",
            unique_together={("building", "number")},
        ),
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together={("user", "apartment")},
        ),
        migrations.AlterUniqueTogether(
            name="building",
            unique_together={("complex", "number")},
        ),
    ]
