# Generated by Django 5.2.17 on 2026-10-02 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="residentialcomplex",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="Используется, если файл не загружен",
                max_length=500,
                verbose_name="Обложка (ссылка)",
            ),
        ),
        migrations.AlterField(
            model_name="residentialcomplex",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="complexes/", verbose_name="Обложка (файл)"
            ),
        ),
        migrations.CreateModel(
            name="ApartmentPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="apartments/", verbose_name="Файл"
                    ),
                ),
                (
                    "url",
                    models.URLField(blank=True, max_length=500, verbose_name="Ссылка"),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Подпись"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="catalog.apartment",
                        verbose_name="Квартира",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото квартиры",
                "verbose_name_plural": "Фото квартир",
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="ComplexPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="complexes/gallery/", verbose_name="Файл"
                    ),
                ),
                (
                    "url",
                    models.URLField(blank=True, max_length=500, verbose_name="Ссылка"),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Подпись"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "complex",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="catalog.residentialcomplex",
                        verbose_name="ЖК",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото ЖК",
                "verbose_name_plural": "Фото ЖК",
                "ordering": ("order", "id"),
            },
        ),
    ]
