# Generated by Django 5.2.17 on 2026-09-29 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MortgageProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(max_length=128, verbose_name="Банк")),
                ("name", models.CharField(max_length=128, verbose_name="Программа")),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Ставка, % годовых"
                    ),
                ),
                (
                    "min_down_payment_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=20,
                        max_digits=5,
                        verbose_name="Мин. первый взнос, %",
                    ),
                ),
                (
                    "max_term_years",
                    models.PositiveSmallIntegerField(
                        default=30, verbose_name="Макс. срок, лет"
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=30000000,
                        max_digits=14,
                        verbose_name="Макс. сумма кредита, ₽",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Условия")),
                (
                    "badge",
                    models.CharField(
                        blank=True,
                        help_text="Например: «Господдержка»",
                        max_length=32,
                        verbose_name="Метка",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#0f766e", max_length=16, verbose_name="Цвет"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
            ],
            options={
                "verbose_name": "Ипотечная программа",
                "verbose_name_plural": "Ипотечные программы",
                "ordering": ("rate",),
            },
        ),
        migrations.CreateModel(
            name="MortgageApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "property_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="Стоимость недвижимости",
                    ),
                ),
                (
                    "down_payment",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="Первоначальный взнос",
                    ),
                ),
                (
                    "term_years",
                    models.PositiveSmallIntegerField(verbose_name="Срок, лет"),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Ставка"
                    ),
                ),
                (
                    "loan_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Сумма кредита"
                    ),
                ),
                (
                    "monthly_payment",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="Ежемесячный платёж",
                    ),
                ),
                (
                    "monthly_income",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="Ежемесячный доход",
                    ),
                ),
                (
                    "employment",
                    models.CharField(
                        choices=[
                            ("hired", "Работа по найму"),
                            ("business", "Собственный бизнес"),
                            ("self", "Самозанятый / ИП"),
                            ("other", "Другое"),
                        ],
                        default="hired",
                        max_length=16,
                        verbose_name="Занятость",
                    ),
                ),
                ("full_name", models.CharField(max_length=255, verbose_name="ФИО")),
                ("phone", models.CharField(max_length=32, verbose_name="Телефон")),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата рождения"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("in_review", "На рассмотрении в банке"),
                            ("approved", "Одобрена"),
                            ("rejected", "Отказ"),
                            ("cancelled", "Отозвана клиентом"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "manager_comment",
                    models.TextField(blank=True, verbose_name="Комментарий менеджера"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "apartment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mortgage_applications",
                        to="catalog.apartment",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mortgage_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="mortgage.mortgageprogram",
                        verbose_name="Программа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на ипотеку",
                "verbose_name_plural": "Заявки на ипотеку",
                "ordering": ("-created_at",),
            },
        ),
    ]
