# Generated by Django 5.2.17 on 2026-09-29 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Новый Горизонт",
                        max_length=128,
                        verbose_name="Название",
                    ),
                ),
                (
                    "slogan",
                    models.CharField(blank=True, max_length=255, verbose_name="Слоган"),
                ),
                ("about", models.TextField(blank=True, verbose_name="О компании")),
                ("mission", models.TextField(blank=True, verbose_name="Миссия")),
                (
                    "founded_year",
                    models.PositiveSmallIntegerField(
                        default=2004, verbose_name="Год основания"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=32, verbose_name="Телефон"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Офис продаж"
                    ),
                ),
                (
                    "work_hours",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Часы работы"
                    ),
                ),
                (
                    "inn",
                    models.CharField(blank=True, max_length=16, verbose_name="ИНН"),
                ),
                (
                    "built_sqm",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Построено, тыс. м²"
                    ),
                ),
                (
                    "houses_built",
                    models.PositiveIntegerField(default=0, verbose_name="Сдано домов"),
                ),
                (
                    "families",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Семей получили ключи"
                    ),
                ),
                (
                    "advantages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"icon":"...","title":"...","text":"..."}]',
                        verbose_name="Преимущества",
                    ),
                ),
                (
                    "milestones",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"year":2004,"title":"...","text":"..."}]',
                        verbose_name="История",
                    ),
                ),
                (
                    "purchase_steps",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Шаги покупки"
                    ),
                ),
                (
                    "awards",
                    models.JSONField(blank=True, default=list, verbose_name="Награды"),
                ),
                (
                    "reviews",
                    models.JSONField(blank=True, default=list, verbose_name="Отзывы"),
                ),
                (
                    "faq",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Вопросы и ответы"
                    ),
                ),
            ],
            options={
                "verbose_name": "Информация о компании",
                "verbose_name_plural": "Информация о компании",
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Имя")),
                ("phone", models.CharField(max_length=32, verbose_name="Телефон")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("consult", "Консультация по покупке"),
                            ("mortgage", "Ипотека"),
                            ("visit", "Запись на просмотр"),
                            ("other", "Другое"),
                        ],
                        default="consult",
                        max_length=16,
                        verbose_name="Тема",
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="Сообщение")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("in_progress", "В работе"),
                            ("done", "Обработана"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "manager_comment",
                    models.TextField(blank=True, verbose_name="Комментарий менеджера"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "apartment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="catalog.apartment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на звонок",
                "verbose_name_plural": "Заявки на звонок",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("news", "Новости"),
                            ("promo", "Акции"),
                            ("progress", "Ход строительства"),
                        ],
                        default="news",
                        max_length=16,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "excerpt",
                    models.CharField(blank=True, max_length=400, verbose_name="Анонс"),
                ),
                ("body", models.TextField(blank=True, verbose_name="Текст")),
                ("published_at", models.DateField(verbose_name="Дата публикации")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликовано"),
                ),
                (
                    "complex",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="news",
                        to="catalog.residentialcomplex",
                    ),
                ),
            ],
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
                "ordering": ("-published_at",),
            },
        ),
    ]
